// src/app/[locale]/layout.js
import { NextIntlClientProvider } from 'next-intl';
import { notFound } from 'next/navigation';
import { routing } from '@/i18n/routing'; // Импортируем routing
import getRequestConfig from '@/i18n/request';
// --- Компоненты ---
import Header from '@/app/components/Header/Header'; // Путь к твоему Header
// import Footer from '@/app/components/Footer/Footer'; // Если есть Footer

// --- Остальные импорты ---
import { Geist, Geist_Mono } from "next/font/google"; // Убедись что импорт правильный для v15
import "../globals.css";
import { Analytics } from "@vercel/analytics/react";
import { SpeedInsights } from "@vercel/speed-insights/next";

const geistSans = Geist({ subsets: ['latin'], variable: '--font-geist-sans' }); // Пример настройки для v14/v15
const geistMono = Geist_Mono({ subsets: ['latin'], variable: '--font-geist-mono' });

export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }));
}

export const metadata = {
  title: 'Kuchen', // TODO: Тоже можно сделать переводимым позже
  description: 'Generated by create next app',
};

export default async function LocaleLayout({ children, params }) {
  const { locale } = await params;

  if (!routing.locales.includes(locale)) {
    notFound();
  }

  const messages = (await import(`@/messages/${locale}.json`)).default;

  return (
      <html lang={locale}>
      <head>
        {/* ✅ ВСТАВКА COOKIEFIRST СКРИПТА */}
        <script
            src="https://consent-eu.cookiefirst.com/sites/komastil.de-74061947-f418-45d8-8754-73db55507ecf/consent.js"
            defer
        ></script>
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}> {/* Добавил flex для прижатия футера */}
      {/* Передаем locale и загруженные messages в провайдер */}
      <NextIntlClientProvider locale={locale} messages={messages}>
        {/* Рендерим Header ЗДЕСЬ и передаем ему locales */}
        <Header locales={routing.locales} />

        {/* Основной контент страницы */}
        <main className="flex-grow"> {/* Добавил flex-grow */}
          {children}
        </main>

        {/* Рендерим Footer ЗДЕСЬ (если есть) */}
        {/* <Footer /> */}

      </NextIntlClientProvider>
      <Analytics />
      <SpeedInsights />
      </body>
      </html>
  );
}